checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    excluded_paths:
        - tests/*
build:
    environment:
        python: 3.7
    dependencies:
        before:
            - pip install -r ./dev-requirements.txt
    tests:
        override:
            -
                command: './run_tests.sh'
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
