language: python
dist: xenial
sudo: yes
python:
  - "3.6"
  - "3.7"
  - "pypy3.6"
addons:
install:
  - pip install --upgrade setuptools pytest pytest-cov coveralls
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
before_script:
  - ./show_versions.sh
script:
  - ./run_tests.sh
after_success:
  - coveralls
