version: '2'

services:
  test:
    image: validate_it
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/validate_it/"
    command: bash -c "coverage run --source='./validate_it/' -m pytest tests -vv && coverage combine && coverage report"
