version: '2'

services:
  python3.6_test:
    build:
      context: .
      dockerfile: python3.6.dockerfile
    volumes:
      - "./:/var/validate_it/"
    command: bash -c "find . -name "*.pyc" -type f -delete && coverage run --source='./validate_it/' -m pytest tests -vv && coverage combine && coverage report"

  python3.7_test:
    build:
      context: .
      dockerfile: python3.7.dockerfile
    volumes:
      - "./:/var/validate_it/"
    command: bash -c "find . -name "*.pyc" -type f -delete && coverage run --source='./validate_it/' -m pytest tests -vv && coverage combine && coverage report"

  pypy_test:
    build:
      context: .
      dockerfile: pypy.dockerfile
    volumes:
      - "./:/var/validate_it/"
    command: bash -c "find . -name "*.pyc" -type f -delete && coverage run --source='./validate_it/' -m pytest tests -vv && coverage combine && coverage report"

  python3.6_benchmark:
    build:
      context: .
      dockerfile: python3.6.dockerfile
    volumes:
      - "./:/var/validate_it/"
    command: bash -c "find . -name "*.pyc" -type f -delete && /var/validate_it/run_benchmarks.sh"

  python3.7_benchmark:
    build:
      context: .
      dockerfile: python3.7.dockerfile
    volumes:
      - "./:/var/validate_it/"
    command: bash -c "find . -name "*.pyc" -type f -delete && /var/validate_it/run_benchmarks.sh"

  pypy_benchmark:
    build:
      context: .
      dockerfile: pypy.dockerfile
    volumes:
      - "./:/var/validate_it/"
    command: bash -c "find . -name "*.pyc" -type f -delete && /var/validate_it/run_benchmarks.sh"
